### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by pnorman** [emacsen/changemonger#14]
While running changemonger through app.py on changeset 13175649 I got the following error:

```

DEBUG:root:Retrieving http://api.openstreetmap.org/api/0.6/node/770584876/relations for node 770584876 relations
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/0.6/node/770584876/relations HTTP/1.1" 200 184
DEBUG:root:Retrieving http://api.openstreetmap.org/api/0.6/node/770584878/relations for node 770584878 relations
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/0.6/node/770584878/relations HTTP/1.1" 200 184
DEBUG:root:Retrieving http://api.openstreetmap.org/api/0.6/node/770584881/relations for node 770584881 relations
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/0.6/node/770584881/relations HTTP/1.1" 200 184
INFO:werkzeug:192.168.1.4 - - [19/Sep/2012 14:16:33] "GET /changeset?id=13175649 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/pnorman/osm/changemonger-env/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pnorman/osm/changemonger-env/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/pnorman/osm/changemonger-env/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pnorman/osm/changemonger-env/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pnorman/osm/changemonger-env/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pnorman/osm/changemonger-env/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pnorman/osm/changemonger/app.py", line 88, in display_changeset
    sentence = changemonger.changeset_sentence(cset)
  File "/home/pnorman/osm/changemonger/changemonger.py", line 90, in changeset_sentence
    ele_features = zip(eles, db.matchEach(eles))
  File "/home/pnorman/osm/changemonger/features.py", line 288, in matchEach
    return [self.matchAllSolo(ele) for ele in coll]
  File "/home/pnorman/osm/changemonger/features.py", line 282, in matchAllSolo
    if feature.match(ele):
  File "/home/pnorman/osm/changemonger/features/magic.py", line 45, in match
    return (self._typecheck(ele) and ele['nd'][0] == ele['nd'][-1])
IndexError: list index out of range
```

In the debugger I ran dump()

```
>>> dump()
Local variables in frame

self    
<magic.UnidentifiedPolygon instance at 0x23add40>
ele 
{'changeset': '13175649', 'uid': '651207', 'tags': {}, 'timestamp': '2012-09-19T20:45:53Z', 'nd': [], '_tags': [], 'visible': 'false', 'version': '2', 'user': 'Peter 111', 'type': 'way', 'id': '165596414'  }
>>> dump(self)
Details for instance object at 0x23add40

<magic.UnidentifiedPolygon instance at 0x23add40>
__doc__ 
None
__init__    
<bound method UnidentifiedPolygon.__init__ of <magic.UnidentifiedPolygon instance at 0x23add40>>
__module__  
'magic'
_prominence 
0
_typecheck  
<bound method UnidentifiedPolygon._typecheck of <magic.UnidentifiedPolygon instance at 0x23add40>>
categories  
[]
category    
<bound method UnidentifiedPolygon.category of <magic.UnidentifiedPolygon instance at 0x23add40>>
id  
u'37412160'
match   
<bound method UnidentifiedPolygon.match of <magic.UnidentifiedPolygon instance at 0x23add40>>
name    
'unidentified polygon'
named   
True
plural  
'unidentified polygons'
precision   
3
types   
['way']
```

**Comment by emacsen** [comment]
This is ultimately related to issue 1- the cause of the error you're seeing is that the way has been deleted and Changemonger doesn't have a good way of detecting that with the API.

There are going to be some changes soon that will help with this situation from the api library standpoint for changesets, and then I can put in a condition here, but I'm still not sure how to handle this longer term.

**Comment by ppawel** [comment]
Just for the record, another test case for this is http://www.openstreetmap.org/browse/changeset/13233954.
