### ISSUE TITLE
TypeError: %u format: a number is required, not str

### ISSUE THREAD

**Issue by ppawel** [emacsen/changemonger#20]
`ERROR:__main__:Exception on /api/changeset/13440094 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 143, in show_changeset
    sentence = changemonger.changeset_sentence(cset)
  File "/stuff/src/osm/osm-activity-publishers/changeset-publisher/changemonger/changemonger.py", line 106, in changeset_sentence
    english_list =  elements.grouped_to_english(sorted_features)
  File "/stuff/src/osm/osm-activity-publishers/changeset-publisher/changemonger/elements.py", line 111, in grouped_to_english
    l.append(display_name(elements[0], feature))
  File "/stuff/src/osm/osm-activity-publishers/changeset-publisher/changemonger/elements.py", line 60, in display_name
    return common_name(ele)
  File "/stuff/src/osm/osm-activity-publishers/changeset-publisher/changemonger/elements.py", line 44, in common_name
    return("%u %u" % (a, ele['tags']['operator']))
TypeError: %u format: a number is required, not str`

**Comment by ppawel** [comment]
Same for the other paths:

`ERROR:__main__:Exception on /api/changeset/13278339 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.6/dist-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.6/dist-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.6/dist-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 143, in show_changeset
    sentence = changemonger.changeset_sentence(cset)
  File "/home/ppawel/social/osm-activity-publishers/changeset-publisher/changemonger/changemonger.py", line 106, in changeset_sentence
    english_list =  elements.grouped_to_english(sorted_features)
  File "/home/ppawel/social/osm-activity-publishers/changeset-publisher/changemonger/elements.py", line 111, in grouped_to_english
    l.append(display_name(elements[0], feature))
  File "/home/ppawel/social/osm-activity-publishers/changeset-publisher/changemonger/elements.py", line 60, in display_name
    return common_name(ele)
  File "/home/ppawel/social/osm-activity-publishers/changeset-publisher/changemonger/elements.py", line 41, in common_name
    return("%u %u" % (a, ele['tags']['brand']))
TypeError: %u format: a number is required, not str
INFO:werkzeug:127.0.0.1 - - [15/Oct/2012 21:25:32] "GET /api/changeset/13278339 HTTP/1.1" 500 -`

**Comment by emacsen** [comment]
Super helpful would be a test case here, but I think it's fixed in the lastest github and deployed on the test instance.

**Comment by ppawel** [comment]
You can see changeset ids in the first line of every log I pasted above. However, both changesets work on your test instance, so either it is fixed or it's a problem on my side with the integration stuff.
